resolver: lts-9.12
packages:
- '.'
- location:
    git: https://github.com/mrkkrp/mmark.git
    commit: 35428e2dbce161d3e1d3688510ed338ec38a5904
  extra-dep: true
extra-deps:
- megaparsec-6.2.0
- modern-uri-0.1.1.0
- parser-combinators-0.2.0
