resolver: lts-9.12
packages:
- '.'
- location:
    git: https://github.com/mrkkrp/mmark.git
    commit: 7a08a66527cbbcbed4a6437a1be760b485442652
  extra-dep: true
extra-deps:
- megaparsec-6.2.0
- modern-uri-0.1.1.0
- parser-combinators-0.2.0
